### ISSUE TITLE
Analyze if we can reuse some logic and UI components for MMB from mobile repository.

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#146]
Because MMB for the margarita will be very similar to what we have in the current mobile react-native app, we would like to reuse code how much as a possible. 

The new designs for MMB are here https://www.figma.com/file/BNs81bMp3VVuxqKIICbnNvqd/MMB but if is possible reuse code from mobile, we will take as design reference current mobile implementation, but keep an eye also on the universal-components if it possible use components form them.

So pls write down your summary about reuse code possibility, if it will be hard we will start from scratch.

**Comment by tbergq** [comment]
I think first of all, we should know if MMB support will be added to tequila. 
• If yes, we should mock endpoints in margarita graphql
• If no, we should rather use login and MMB endpoint from our own graphql. 

If we use endpoints from our own graphql, most of MMB should be ready to be added as is with small modifications. 

Note that we deleted MMB from our repo, since there is no active development there. To extract code from MMB, one should create a separate branch and revert commit `94025231`

We used some native dependencies in MMB
• `react-native-fecth-blob` -> it is supported in Expo
• `react-native-share` -> there is some share functionality in expo
• `react-native-pdf` -> not in expo, but we could check [this](https://github.com/xcarpentier/rn-pdf-reader-js)
• `wallet-integration` -> Apple policy says we can only use apple's UI button to add content to apple wallet. We can not achieve this functionality without eject. So I we skip it.
• `react-native-zip-archive` -> pkpass (mobile-ticket) is a zip file, we need to unzip it to show details for mobile ticket on android. Not supported in Expo. Since this is just the android solution for `apple-wallet` I suggest we skip this as well.

**Comment by MRTNKCR** [comment]
I already sent the request regarding the Tequila MMB API yesterday, still waiting for a response, pinged them once again...

**Comment by FilipMessa** [comment]
The result is there is no API for manage my booking (MMB) in Tequila, but there are plans for that.
So we can start on that recycle what we can from mobile and mock data for it.

@MRTNKCR is that right?

**Comment by FilipMessa** [comment]
Done!
