### ISSUE TITLE
Implement save_booking from Booking API

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#536]
Tequila Booking API `save_booking` request initiates the booking on Tequila backend and should be called before starting booking payment flow.
Request is quite similar to `check_flights` so we can probably use similar schema ( related issue #114 ).
The main difference in response is the extra `transaction_id` which is then used for payment confirmation. Also this request requires more detailed passengers info in parameters. 

Booking API documentation:
https://tequila.kiwi.com/portal/resources/booking_api
https://tequila.kiwi.com/portal/resources/booking_and_payment_flow

**Comment by aalises** [comment]
Proposal for `/booking/save_booking` implementation from Booking API https://tequila.kiwi.com/portal/resources/booking_api.

We need this API call in order to save the booking when going to the confirm payment screen. This initiates the process on the backend of reserving the booking and waiting for price confirmation. it is a **POST** request.

Mutation name:

```
saveBooking
```

Input:

```
input SaveBookingInput {
 payment_gateway: String!
}
```
According to the docs, `payment_gateway` is mandatory but only should be put to `payu` when paying with `Zooz`, doesn't specify the value when paying with credits...

Payload / Body Request:
```
type SaveBookingPayload {
  """Token received in search results"""
  bookingToken: String!

  """Number of checked bags for the booking"""
  bags: Int!

  """Information about the passengers traveling such as name, nationality, etc"""
  passengers: [Passenger]

  """Language and Locale of the booking"""
  lang: LanguageInput

  """Choose currency for the booking and the conversion is done on the backend and returned on EUR"""
  currency: String
}

type LanguageInput {
  language: String,
  locale: String
}
```
This is a WIP as `Passenger` take more fields than the actual implementation. @TODO: extend `Passenger` with the new fields.

Output:
```
type SaveBookingResponse {
  """
  Unique ID of the transaction which then can be used to identify the booking in subsequent calls e.g confirm payment
  """
  transactionId: String!,
  itinerary: ItineraryInterface!
}
```

**Comment by tbergq** [comment]
Looks good, except for `payment_gateway` being in snake_case. Should probably be `paymentGateway`

Maybe we should also return passengers with the response 🤔

**Comment by JoseDuSV** [comment]
👍 I think this will work. Thanks
