### ISSUE TITLE
[Button] Add size prop like on Orbit components

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#590]
**Is your feature request related to a problem? Please describe.**
The button currently has a fixed height of 44; I would need to have the same size props as on Orbit components: https://kiwicom.github.io/orbit-components/?selectedKind=Button&selectedStory=Playground&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by KarinaDavtyan** [comment]
The Button component might need  more refactoring to add size prop.
For example,  the fontSize in universal components is **16** which corresponds to `fontSizeButtonLarge` and in orbit button is **14** for `normal` type.
Should we change it for the token values, no? 
Like fontSize  **12**, **14** and **16** for `small`, `normal`, `large` correspondingly @JoseDuSV

**Comment by JoseDuSV** [comment]
@KarinaDavtyan Adding size prop like in Orbit is a good idea.
I'm just not sure about size values and what should we use as source of truth.
Because in all our current Margarita designs font size for normal buttons seems to be 16 as you've mentioned.
But then there is this relatively new document https://www.figma.com/file/7pVyYhhKgQdkdj7PRQnVrm/Tokens?node-id=779%3A46 where values corresponds to Orbit.

So I'm for using **Orbit** values, because we don't have small and big Margarita buttons designs anyway (at least I cannot find them anywhere) and if we will need normal font to be **16** for Margarita. I can then extend ThemeProvider to override this value.

**Comment by KarinaDavtyan** [comment]
@RobinCsl @JoseDuSV Do we still need `sublabel` prop? Couldn't find it anywhere used in margarita

**Comment by RobinCsl** [comment]
This would be for another task to remove it. The current focus should just be about the size of the button.

**Comment by JoseDuSV** [comment]
Agree, we probably don't need it, but it can be removed later.
