### ISSUE TITLE
Refactor Modals to not be directly connected to Context

### ISSUE THREAD

**Issue by aalises** [kiwicom/margarita#700]
Currently, Each `SearchForm`component (e.g `DatePickers`) is connected to the `SearchContext`. That means that every time that you update a value, it is also directly updated on the context, hence triggering a render on all components connected to it, and also triggering the `Search`API calls.

**Proposal:** Update the `SearchForm` to make all the values be set as the local state of the component. when clicking search, the `OnSubmit` callback is called with all the params, and then, after the validation passes (no empty fields, whatever), they are all set at once on the context.

This way the application is only updated / API calls are only made on clicking search, and not every time a parameter is changed, which creates unnecessary calls.

This way we can also clean up the context a little bit such as not having the modal types there.

WDYT @jvaclavik @tbergq @JoseDuSV @KarinaDavtyan @RobinCsl

**Comment by tbergq** [comment]
This is the way kiwi.com FE works, when you change a parameter, it performs a new search, so that is ok. 

I definitely agree that modal types should not be in the context and should be refactored. This is based on our first modal being really bad, so this was the only way to make it work. But it should be ready to be improved now.

**Comment by JoseDuSV** [comment]
I basically agree with @tbergq . Performing search after params change is ok for me.
But handling modals through Search context is no longer necessary. So we can definitely clean up all `ModalTypes` related stuff.
