### ISSUE TITLE
Update the Expo to new version 33.0.0

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#877]

**Comment by AdrienV** [comment]
Hi, 

Did you find a solution for this issue ? Expo ask for V34.0.0 now.

**Comment by RobinCsl** [comment]
Hi Adrien,

This project is not actively maintained anymore.

There is this unfinished PR though: https://github.com/kiwicom/margarita/pull/921

If there was something to be said to our managers in Kiwi.com for Margarita to be given more attention, what would it be?

Thanks for your interest!

**Comment by AdrienV** [comment]
Hi Robin, 

Thanks for your reply.

> If there was something to be said to our managers in Kiwi.com for Margarita to be given more attention, what would it be?

I don't know at the moment, I am only trying to use the package as "starter" to replacing our current mobile app developed w/ travelpayout's SDK (https://www.travelpayouts.com/sdk/)
They have a fully functional application, but they are native app difficult to maintain / upgrade for inexperienced developer w/ native app. I am more efficient w/ JS techs, and I like a lot Kiwi processes & flight searches (very efficient for specific case like airports transfert), it's for this reason I am starting to use this repo ;) 
I hope it was your question, my english is not so good :/

**Comment by RobinCsl** [comment]
Hi Adrien,

We could switch to French if that's easier ;) Don't hesitate to DM me on [Twitter](https://twitter.com/RobinCsl) if you'd like to discuss further.

It was indeed my question, and thanks for providing details. I've forwarded this internally and someone might get in touch with you.

The idea behind Margarita was to provide an example usage of the [Tequila API](https://tequila.kiwi.com/).

Expo has now come a long way since we started this project, and cross-platform-ness can be achieved in a much easier way now, almost out of the box with Expo and `react-navigation` as far as I know, since they both support web as a target.
