### ISSUE TITLE
[General Enquiry] Is the Margarita GDPR compliant ?

### ISSUE THREAD

**Issue by sebastiancretu** [kiwicom/margarita#922]
Hi,

I would like to know if Margarita is GDPR compliant, because in the demo i didn't see any popup related to cookie policy or privacy policy.

Thank you.

**Comment by JosefDuda** [comment]
Hello @sebastiancretu GDPR consent window is not implemented in the Margarita demo app, since it shows just example `search -> booking` user flow without actually storing any real data about the user. 

If you want to use it in production, you'll need to implement it yourself. There is for example `Modal` component for this use case, which you can just fill with propper content https://kiwicom-universal-components.netlify.com/?selectedKind=Modal.

**Comment by sebastiancretu** [comment]
Ok. Thank you for the info.
